version: '3.8'

services:

  nginx:
    container_name: testing__nginx
    build: ./docker/nginx
    volumes:
      - .:/src:delegated
    ports:
      - 8888:80

  php-fpm:
    env_file:
      - .env.local
    container_name: testing__php-fpm
    build: ./docker/php-fpm
    volumes:
      - .:/src:delegated
    ports:
      - 9001:9000

  php-cli:
    env_file:
      - .env.local
    container_name: testing__php-cli
    build: ./docker/php-cli
    volumes:
      - .:/src:delegated
      - composer_cache:/home/appuser/.composer/cache:delegated


  mysql:
    env_file:
      - .env.local
    container_name: testing__mysql
    build: ./docker/mysql
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    command: --sql_mode=""
    environment:
      MYSQL_USER: testing
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_PASSWORD: testing
      MYSQL_DATABASE: testing_db
      SERVICE_NAME: mysql
      TZ: Asia/Baku
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306

volumes:
  composer_cache:
  mysql_data: